name       : python-maturin
version    : 0.11.4
release    : 8
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.11.4.tar.gz : 9d4fa5f0b556bd05204f27d465771573a0ff54262b118df0151cd3f13c3ec219
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
