name       : python-maturin
version    : 0.14.8
release    : 25
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.14.8.tar.gz : f774862c7321aa80c68bb41f0b0e611aa8d75c2fec5d53b24009c7cf9d394e4d
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-setuptools-rust
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
