name       : python-maturin
version    : 0.14.10
release    : 27
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.14.10.tar.gz : 8fc9bcdcb7f1535d5e3e8bb500c348ca1bff5a6dce87b0ab7dbc5a49723da28a
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-setuptools-rust
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
