name       : python-maturin
version    : 0.11.3
release    : 7
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.11.3.tar.gz : e65864a36be44456da0f9174de12fe3ea02bb87a968b5333ace3b122869dd6b2
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
