name       : python-maturin
version    : 0.11.2
release    : 5
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.11.2.tar.gz : 4c37b25c327fedf46c0b0833d0e8a5c69e9edcdfeb5b6c946b94198001044f1d
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
