name       : python-maturin
version    : 1.0.1
release    : 34
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v1.0.1.tar.gz : c4141615078313a5afbb581fefc4b3673c24466d37c939dc44a816a265067c74
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-setuptools-rust
    - python-tomli
build      : |
    export MATURIN_SETUP_ARGS="--features full,rustls"
    %python3_setup
install    : |
    %python3_install
