name       : python-maturin
version    : 0.12.9
release    : 14
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.12.9.tar.gz : 26b094c20c9939cc9df5632b4b8d8921c4086b27a4867b439297e616f5781716
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
