name       : python-maturin
version    : 0.10.6
release    : 1
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.10.6.tar.gz : e6a9a67cc62ffe248654e60e7ec211bf23319c4c936ad87022f7a1fd0997430d
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
