name       : python-maturin
version    : 0.12.20
release    : 24
source     :
    - https://github.com/PyO3/maturin/archive/refs/tags/v0.12.20.tar.gz : 5a1c9ed2acd8ea1edbe7e8b7ed78f2f6887eff77f696dbdd93f81b606960efbe
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
description: |
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages.
builddeps  :
    - cargo
    - python-setuptools-rust
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
